<?php
// Texte pt script (Romana)
$ro_site = [
  'chat'=>'Chat',
  'name'=>'Nume',
  'code'=>'Cod',
  'addnmcd'=>'Adaugati un Nume si acest Cod',
  'chatlogged'=>'<h4 id="chlogged">Ca sa adaugati text in chat, trebuie sa fiti autentificat.</h4>',
  'online'=>'Online',
  'no1online'=>'- Nimeni online',
  'loadroom'=>'<h3>Incarcare Camera-Chat</h3>',
  'notchat'=>'Aceasta camera e goala.',
  'addurl'=>'Adaugati URL fara http://',
  'logoutchat'=>'Iesire din Chat',
  'enterchat'=>'Buna <b>%s</b> Intrati in Chat',
  'emptyroom'=>'Selectati o camera de chat care sa fie golita',
  'cadmpass'=>'Parola Admin:',
  'sbmemptyroom'=>'Golire Camera Chat',
  'emptedroom'=>'Camera de chat: <b>%s</b> este golita',
  'err_emptedroom'=>'Nu poate goli camera de chat: ',
  'err_savechat'=>'Nu poate salva datele in: %s , sau fisierul nu poate fi creat',
  'err_name'=>'Numele trebuie sa contina intre 2 si 15 caractere: Litere, Numere, Spatiu si Liniute.',
  'err_nameused'=>' - e deja folosit. Alegeti alt nume',
  'err_vcode'=>'Adaugati corect codul de verificare',
  'err_textchat'=>'Textul trebuie sa contina intre 2 si 230 caractere',
  'err_addurl'=>'Adresa URL incorecta. Adaugati URL fara http://  Exemplu: www.marplo.net/ajax/',
  'err_adminpass'=>'<h3 style="margin:2em auto 2em 40%; color:#fe0100;">Parola Incorrecta</h3>'
];

// Texte pt script (Engleza)
$en_site = [
  'chat'=>'Chat',
  'name'=>'Name',
  'code'=>'Code',
  'addnmcd'=>'Add a Name, and this code',
  'chatlogged'=>'<h4 id="chlogged">To can add texts in chat, you must be logged in.</h4>',
  'online'=>'Online',
  'no1online'=>'- No-one online',
  'loadroom'=>'<h3>Loadding Chat-Room</h3>',
  'notchat'=>' &bull; Not chat added in this room.',
  'addurl'=>'Add URL without http://',
  'logoutchat'=>'Logout from Chat',
  'enterchat'=>'Hi <b>%s</b> Enter the Chat',
  'emptyroom'=>'Select a Chat-Room to empty',
  'cadmpass'=>'Admin Password:',
  'sbmemptyroom'=>'Empty Chat-Room',
  'emptedroom'=>'The chat room: <b>%s</b> is empty',
  'err_emptedroom'=>'Cannot empty the chat room: ',
  'err_savechat'=>'Unable to save data in: %s , or the file cannot be created',
  'err_name'=>'The name must contain between 2 and 15 characters: Letters, Numbers, Space, Dash, and _',
  'err_nameused'=>' - is already used. Choose another nickname',
  'err_vcode'=>'Add correct verification code',
  'err_textchat'=>'The text must contain between 2 and 230 characters',
  'err_addurl'=>'Incorrect URL format. Add URL without http://  Example: coursesweb.net/ajax/',
  'err_adminpass'=>'<h3 style="margin:2em auto 2em 40%; color:#fe0100;">Incorrect Password</h3>'
];